### ISSUE TITLE
Code example flickers when scrolling

### ISSUE THREAD

**Issue by dufferzafar** [knipferrc/teacup#5]
Perhaps we need to use viewport's high performance rendering to improve this?

https://github.com/charmbracelet/bubbles/blob/7959eb486708b841f703fd26ed6429a04f26a4c4/viewport/viewport.go#L45-L53

**Comment by mistakenelf** [comment]
@dufferzafar do you have more information you could share with the flickering. I am not able to reproduce any flickering when scrolling on the code example

**Comment by Vinschni** [comment]
Try using another terminal software. Using powershell terminal on windows e.g.
