### ISSUE TITLE
Icons not showing properly

### ISSUE THREAD

**Issue by fniu** [knipferrc/teacup#6]
Hi,

I have run filetree locally without any changes on both windows and linux (WSL2) and ran into issues with file icons. They don't seem to show properly.

Please see the not-found icons in the screenshot below. 

![Skärmbild 2022-06-21 145444](https://user-images.githubusercontent.com/1160165/174804639-eb048c0a-8933-4b46-9170-2fcf75a5a96f.png)

**Comment by mistakenelf** [comment]
@fniu for the icons to work properly you'll need to make sure you have a nerd font installed. You can find them here https://www.nerdfonts.com/

**Comment by fniu** [comment]
Aha, thanks for the info!
