### ISSUE TITLE
$ go install github.com/knipferrc/teacup@latest package github.com/knipferrc/teacup is not a main package

### ISSUE THREAD

**Issue by olivertzeng** [knipferrc/teacup#7]
$ go install github.com/knipferrc/teacup@latest
package github.com/knipferrc/teacup is not a main package

**Comment by mistakenelf** [comment]
Updated the readme instructions should be `go get github.com/knipferrc/teacup@latest`

**Comment by olivertzeng** [comment]
thanks! can i translate your project to zh_TW? @knipferrc
