### ISSUE TITLE
❯ go get github.com/knipferrc/teacup@latest go: package github.com/knipferrc/teacup is in the main module, so can't request version latest

### ISSUE THREAD

**Issue by olivertzeng** [knipferrc/teacup#8]
yo

**Comment by mistakenelf** [comment]
Not sure why your getting that, works in every project that I have tried

**Comment by git-girl** [comment]
hey, i got the same error. i know nothing about go and cant properly help, but can i provide some logs that would helpful if you couldn't reproduce the errror?
